### ISSUE TITLE
TypeError: (0 , _dndCore2.default) is not a function

### ISSUE THREAD

**Issue by potapovDim** [gaearon/dnd-core#33]
```
import DragDropManager from 'dnd-core'
import createTestBackend  from 'dnd-core'

 let manager;
  let backend;
  let registry;

  beforeEach(() => {
    manager = DragDropManager(createTestBackend);
    backend = manager.getBackend();
    registry = manager.getRegistry();
  });
```

get error 

TypeError: (0 , _dndCore2.default) is not a function

**Comment by hawkrives** [comment]
You're importing the `default` export from `dnd-core`, when you want to import certain *named exports*.

```
import { DragDropManager, createTestBackend } from 'dnd-core'
```

should do it.

**Comment by potapovDim** [comment]
![screen shot 2016-08-11 at 4 14 03 pm](https://cloud.githubusercontent.com/assets/19333856/17589660/ac01e3d4-5fde-11e6-9e04-4271bfe0e2dd.png)
i did like this before

**Comment by hawkrives** [comment]
All I can tell you is that that's why it's not working – you're importing the same thing twice, and giving it different names – and that thing doesn't actually exist. If you want to import a thing with a name, you have to use the braces.

See https://tonicdev.com/hawkrives/57ac76d774054114008fc046

You could try 

```js
const {DragDropManager, createTestBackend} = require('dnd-core')
```

and see if your setup just doesn't like named es2015 imports.
